#ifndef _FCD_BLOCKS_PATTERNS_H_
#define _FCD_BLOCKS_PATTERNS_H_

/* enum fcd_blocks_patterns */

#define BLOCK_PATTERN_BLOCK_BEGIN "/block '*'/"
#define BLOCK_PATTERN_BLOCK_END "\\block\\"

#define BLOCK_PATTERN_TITLE_BEGIN "/title/"
#define BLOCK_PATTERN_TITLE_END "\\title\\"

#define BLOCK_PATTERN_TEXT_BEGIN "/text/"
#define BLOCK_PATTERN_TEXT_END "\\text\\"

#define BLOCK_PATTERN_IMAGE_BEGIN "/img '*'/"
#define BLOCK_PATTERN_IMAGE_END "\\img\\"

#define BLOCK_PATTERN_LINK_BEGIN "/link '*'/"
#define BLOCK_PATTERN_LINK_END "\\link\\"

#define BLOCK_PATTERN_CODE_BEGIN "/code/"
#define BLOCK_PATTERN_CODE_END "\\code\\"

#define BLOCK_PATTERN_TEXT_MOD_BOLD_BEGIN "/b/"
#define BLOCK_PATTERN_TEXT_MOD_BOLD_END "\\b\\"

#define BLOCK_PATTERN_TEXT_MOD_MARK_BEGIN "/m/"
#define BLOCK_PATTERN_TEXT_MOD_MARK_END "\\m\\"

#define BLOCK_PATTERN_TEXT_MOD_ITALIC_BEGIN "/i/"
#define BLOCK_PATTERN_TEXT_MOD_ITALIC_END "\\i\\"

#define BLOCK_PATTERN_TEXT_MOD_DELETE_BEGIN "/d/"
#define BLOCK_PATTERN_TEXT_MOD_DELETE_END "\\d\\"

#define BLOCK_PATTERN_TEXT_MOD_UNDERLINE_BEGIN "/u/"
#define BLOCK_PATTERN_TEXT_MOD_UNDERLINE_END "\\u\\"

#define BLOCK_PATTERN_TEXT_MOD_SUBSCRIPT_BEGIN "/sub/"
#define BLOCK_PATTERN_TEXT_MOD_SUBSCRIPT_END "\\sub\\"

#define BLOCK_PATTERN_TEXT_MOD_SUPERSCRIPT_BEGIN "/sup/"
#define BLOCK_PATTERN_TEXT_MOD_SUPERSCRIPT_END "\\sup\\"

extern char** block_patterns_array;

#endif /* _FCD_BLOCKS_PATTERNS_H_ */
